num1=int(input ("enter your number: "))
num2=int(input ("enter your number: "))
num3=int(input ("enter your number: "))
num4=int(input ("enter your number: "))
num5=int(input ("enter your number: "))
print (num5//num4)
print (num2*num3)
print (num1+num5)
print (num3-num5)
print (num4%num3)